root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
args_bin = []
bin = "./tmp/main.exe"
cmd = "go build -o ./tmp/main.exe ./cmd/server/main.go"
delay = 100
exclude_dir = ["node_modules", "vendor", "tmp", "bin"]
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = false
follow_symlink = false
include_ext = ["go", "html", "css", "js"]
kill_delay = "0s"
log = "build-errors.log"
send_interrupt = false
stop_on_root = false

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false

[misc]
clean_on_exit = true